line="Shell:scripting:is:fun."
IFS=:
set $line
echo $1
echo $2
echo $3
echo $4
IFS=''
set $line
echo $1
echo $2
echo $3
echo $4

#PROGRAM ZA DEMONSTRACIJU PROMENLJIVE IFS(INTERNAL FIELD SEPARATOR) KOJA
#OREDJUJE STA BASH TRETIRA KAO RAZMAK IZMEDJU RAZLICITIH POLJA U TERMINALU.
#SET KOMANDA NA OSNOVU OVOG ODREDJUJE NA RAZLICITE NACINE SVOJE POZICIONE 
#PARAMETRE.
