#!/bin/bash
read -t10 x
if [ $? -eq 0 ]
then 
	echo "uspeh" 
else 
	echo "Niste nista uneli" 
fi

#NAPOMENA: FUNKCIONALNOST read -t ZA ODBROJAVANJE UNOSU NE POSTOJI U DASH-U
#TE STOGA NIJE POSIX-COMPATIBLE I NE IZVRSAVA SE KOMANDOM sh. STOGA VALJA
# SPECIFICIRATI S SHABANGOM NA POCETKU DA SE IZVRSAVA U BASH-U IAKO UBUNTU
#TO PO DEFAULTU RADI.
